version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: productos-app
    ports:
      - "8080:8080"
    networks:
      - productos-network

networks:
  productos-network:
    driver: bridge